version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: cache.sh
      runas: ubuntu
  ApplicationStart:
    - location: install.sh
      runas: ubuntu
      