
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
      
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: Abhi
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: 0072707

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run: sudo apt-get install postgresql-client
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
   
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd myproject
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
