
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Zipping Files
          command: |
            pwd
            ls -al
            zip -r web_app.zip . -i web_app/
            echo "Zip Done"
            sudo chmod 775 web_app.zip
            ls -al
      - aws-s3/copy:
          from: web_app.zip
          to: s3://codedeploy.abhithakkar.me
workflows:
  deploy_application:
    jobs:
      - build
      #comments
  #     - aws-code-deploy/deploy:
  #         application-name: csye6225-web_app
  #         bundle-bucket: codedeploy-kmvanesa-me
  #         bundle-key: web_app.zip
  #         deployment-group: csye6225-webapp-deployment
  #         service-role-arn: arn:aws:iam::708581696554:roleCodeDeployServiceRole



